# -*- coding: utf-8 -*-
"""automatizacion-contable-python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kk7GKoZYnd4Hy9EhRIXljQyLq1jnmizQ
"""

# Definicion del estado actual de las cuentasprincipales del libro mayor
libro_mayor = {'Activo': 850, 'Pasivo': 500, 'Ingresos': 300, 'Patrimonio': 1000}

# ingreso de un movimiento que afecta el saldo, en este caso generando una cuenta con saldo negativo
libro_mayor ["Gastos"]=-1200

# Inicializacion de un contenedor para aislar las cuentas que presentan anomalias (saldos negativos)
cuentas_en_rojo= {}

# Recorrido del libro mayor para identificar excepciones contables que requieren auditoria o ajuste
for cuenta, saldo in libro_mayor.items():
  if saldo < 0:
    cuentas_en_rojo[cuenta]=saldo

# salida de resultados para la toma de decisiones sobre las cuentas criticas identificadas
print(f"cuentas en rojo: {cuentas_en_rojo}")